# Generated by Django 5.2 on 2026-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
